create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

create table if not exists public.hon_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  expiration_time bigint,
  user_agent text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create table if not exists public.hon_reminders (
  user_id uuid not null references auth.users(id) on delete cascade,
  id text not null,
  title text not null,
  body text not null default '',
  next_at timestamptz not null,
  repeat_type text not null default 'none' check (repeat_type in ('none','daily','weekly','monthly','interval')),
  interval_value integer not null default 1 check (interval_value > 0),
  interval_unit text not null default 'days' check (interval_unit in ('days','weeks','months')),
  active boolean not null default true,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

create index if not exists hon_reminders_due_idx on public.hon_reminders (next_at) where active;
create index if not exists hon_push_subscriptions_user_idx on public.hon_push_subscriptions (user_id) where active;

alter table public.hon_push_subscriptions enable row level security;
alter table public.hon_reminders enable row level security;

drop policy if exists "Users manage their HON push subscriptions" on public.hon_push_subscriptions;
create policy "Users manage their HON push subscriptions"
on public.hon_push_subscriptions for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their HON reminders" on public.hon_reminders;
create policy "Users manage their HON reminders"
on public.hon_reminders for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- לאחר פריסת פונקציית hon-reminders ושמירת הסודות, מריצים פעם אחת גם את הקטע הבא.
-- יש להחליף את שתי הדוגמאות בערכים של פרויקט Supabase שלך.
--
-- select vault.create_secret('https://PROJECT_REF.supabase.co', 'hon_project_url');
-- select vault.create_secret('YOUR_CRON_SECRET', 'hon_cron_secret');
--
-- select cron.schedule(
--   'hon-reminders-every-minute',
--   '* * * * *',
--   $$
--   select net.http_post(
--     url := (select decrypted_secret from vault.decrypted_secrets where name = 'hon_project_url') || '/functions/v1/hon-reminders?action=dispatch',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'X-Cron-Secret', (select decrypted_secret from vault.decrypted_secrets where name = 'hon_cron_secret')
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
